import localFont from "next/font/local";
import "./globals.css";
import cx from "classnames";
import { Montserrat } from "next/font/google";
import { montserrat } from "./fonts";
import { DarkModeProvider } from "./utils/darkMode/indedx";
import Container from "./componen/router";
import Header from "./componen/layout/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cx(montserrat, montserrat.className)}>
        <DarkModeProvider>
          <Header />
          <Container>{children}</Container>
        </DarkModeProvider>
      </body>
    </html>
  );
}
