import localFont from "next/font/local";
import "./globals.css";
import cx from "classnames";
import { Montserrat } from "next/font/google";
import { montserrat } from "./fonts";
import Header from "./componen/layout/header";
import Content from "./componen/home/content";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={(montserrat, montserrat.className)}>
        <Header />
        <Content />
        {children}
      </body>
    </html>
  );
}
